language: objective-c
matrix:
  include:
    - osx_image: xcode11.6
      env: 'SIMULATOR="name=iPad Pro (12.9-inch) (2nd generation),OS=11.2"'
    - osx_image: xcode11.6
      env: 'SIMULATOR="name=iPhone 7 Plus,OS=10.3.1"'
    - osx_image: xcode11.6
      env: 'SIMULATOR="name=iPad (5th generation),OS=10.3.1"'

before_install:
  - rm -rf ~/Library/Logs/DiagnosticReports/
  - xcrun simctl list
  - brew update
  - gem install bundler
  - gem install fastlane
install:
  - if [ -z "$(brew ls --versions coreutils)" ] ; then brew install coreutils ; fi
  - gem install xcpretty --no-document --quiet
script:
  - ./scripts/ci.sh "${SIMULATOR}"
after_failure:
  - xcrun xcresulttool get --path **/*.xcresult --format json > output/result.json
  - log show "output/system_logs-iPhone 5s_iOS_10.3.1.logarchive/logdata.LiveData.tracev3"
  - ls output/**/*
  - ls **/*
  - sleep 60 && ls ~/Library/Logs/**/*
  - cat output/result.json
  - cat **/*.log
  - sleep 60 && ls ~/Library/Logs/DiagnosticReports/**/*
  - cat ~/Library/Logs/DiagnosticReports/**/*.crash
  - cat **/*.crash
